services:
  flowise:
    ports:
      - 127.0.0.1:3001:3001

  open-webui:
    ports:
      - 127.0.0.1:8080:8080

  n8n:
    ports:
      - 127.0.0.1:5678:5678

  qdrant:
    ports:
      - 127.0.0.1:6333:6333
      - 127.0.0.1:6334:6334

  neo4j:
    ports:
      - 127.0.0.1:7473:7473
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687

  langfuse-worker:
    ports:
      - 127.0.0.1:3030:3030

  langfuse-web:
    ports:
      - 127.0.0.1:3000:3000

  clickhouse:
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9009:9009

  minio:
    ports:
      - 127.0.0.1:9010:9000
      - 127.0.0.1:9011:9001

  postgres:
    ports:
      - 127.0.0.1:5433:5432                

  redis:
    ports:
      - 127.0.0.1:6379:6379

  searxng:
    ports:
      - 127.0.0.1:8081:8080

  ollama-cpu:
    ports:
      - 127.0.0.1:11434:11434

  ollama-gpu:
    ports:
      - 127.0.0.1:11434:11434
      
  ollama-gpu-amd:
    ports:
      - 127.0.0.1:11434:11434

  # Agent development configuration - enables live code reloading
  agent:
    ports:
      - 127.0.0.1:8058:8058  # Direct access to agent for debugging
    volumes:
      # Mount source code for live development (overrides Dockerfile COPY)
      - ../agentic-rag-knowledge-graph:/app:rw
      # Exclude virtual environment to prevent conflicts
      - /app/venv
      - /app/__pycache__
    environment:
      # Enable development mode for faster startup and debugging
      - APP_ENV=development
      - LOG_LEVEL=DEBUG
